remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme 

title: Frank Peter DeVita
description: Bioethics graduate student at NYU studying rationality, decision making, and neuroethics.
